name: Tool Shop E2E

on: [push]

jobs:
  edge:
    runs-on: ubuntu-22.04
    name: E2E on Edge
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: edge
          working-directory: ./tool-shop
  mozilla:
    runs-on: ubuntu-22.04
    name: E2E on Mozilla
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: mozilla
          working-directory: ./tool-shop
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: ./tool-shop
